# Generated by Django 4.2 on 2025-05-16 19:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backend',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('php', 'PHP'), ('python', 'Python'), ('csharp', 'C#'), ('django', 'Django'), ('laver', 'Laver'), ('Go', 'Go')], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fronend',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('js', 'Js'), ('css', 'CSS'), ('html', 'html'), ('figma', 'figma')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tools',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('docker', 'Docker'), ('git', 'Git'), ('webpack', 'Webpack')], max_length=18, null=True),
        ),
    ]
